// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfptekkxptpqoorkxwqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmcHRla2t4cHRwcW9vcmt4d3FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MjUyOTgsImV4cCI6MjA2NjQwMTI5OH0.O-ikfsg490j4CwIOwkKQm15Z7pHRKy5FVkFwvLs_7E0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);